/**
 * Generated by kigu-quant — Rosito Bench
 * Tiny tools. Big solutions.
 *
 * Backend   : LUT
 * Function  : lut_sigmoid
 * Points    : 256
 * Array     : lut_sigmoid
 * Range     : [-6, 6]
 * Type      : int16_t
 * Q-format  : Q1.15
 *
 * Lookup usage:
 *   float val = lut_sigmoid_lookup(x);
 */

#ifndef LUT_SIGMOID_H
#define LUT_SIGMOID_H

#include <stdint.h>

#define LUT_SIGMOID_H_SIZE     256
#define LUT_SIGMOID_H_START    -6.0000000f
#define LUT_SIGMOID_H_END      6.0000000f
#define LUT_SIGMOID_H_STEP     0.047058824f
#define LUT_SIGMOID_H_INV_STEP 21.250000f
#define LUT_SIGMOID_H_SHIFT    15
#define LUT_SIGMOID_H_SCALE    32768LL

static const int16_t lut_sigmoid[LUT_SIGMOID_H_SIZE] = {
    81, 85, 89, 93, 98, 102, 107, 113,
    118, 124, 130, 136, 142, 149, 156, 164,
    172, 180, 188, 197, 207, 217, 227, 238,
    249, 261, 274, 287, 301, 315, 330, 346,
    362, 379, 397, 416, 436, 457, 479, 501,
    525, 550, 576, 603, 632, 661, 693, 725,
    759, 795, 832, 872, 912, 955, 1000, 1046,
    1095, 1146, 1199, 1255, 1313, 1373, 1437, 1503,
    1572, 1643, 1719, 1797, 1878, 1963, 2052, 2145,
    2241, 2341, 2445, 2554, 2667, 2785, 2907, 3034,
    3166, 3303, 3446, 3594, 3747, 3906, 4071, 4242,
    4418, 4601, 4791, 4986, 5189, 5398, 5613, 5835,
    6064, 6300, 6543, 6793, 7050, 7314, 7585, 7863,
    8147, 8439, 8737, 9042, 9353, 9671, 9995, 10325,
    10660, 11001, 11348, 11699, 12056, 12417, 12781, 13150,
    13522, 13898, 14275, 14656, 15038, 15421, 15806, 16191,
    16577, 16962, 17347, 17730, 18112, 18493, 18870, 19246,
    19618, 19987, 20351, 20712, 21069, 21420, 21767, 22108,
    22443, 22773, 23097, 23415, 23726, 24031, 24329, 24621,
    24905, 25183, 25454, 25718, 25975, 26225, 26468, 26704,
    26933, 27155, 27370, 27579, 27782, 27977, 28167, 28350,
    28526, 28697, 28862, 29021, 29174, 29322, 29465, 29602,
    29734, 29861, 29983, 30101, 30214, 30323, 30427, 30527,
    30623, 30716, 30805, 30890, 30971, 31049, 31125, 31196,
    31265, 31331, 31395, 31455, 31513, 31569, 31622, 31673,
    31722, 31768, 31813, 31856, 31896, 31936, 31973, 32009,
    32043, 32075, 32107, 32136, 32165, 32192, 32218, 32243,
    32267, 32289, 32311, 32332, 32352, 32371, 32389, 32406,
    32422, 32438, 32453, 32467, 32481, 32494, 32507, 32519,
    32530, 32541, 32551, 32561, 32571, 32580, 32588, 32596,
    32604, 32612, 32619, 32626, 32632, 32638, 32644, 32650,
    32655, 32661, 32666, 32670, 32675, 32679, 32683, 32687
};

/**
 * Interpolated lookup — O(1), no branches on hot path.
 * Input is clamped to [-6.000000, 6.000000].
 */
static inline float lut_sigmoid_lookup(float x) {
    if (x <= LUT_SIGMOID_H_START) return (float)lut_sigmoid[0] / (float)LUT_SIGMOID_H_SCALE;
    if (x >= LUT_SIGMOID_H_END)   return (float)lut_sigmoid[LUT_SIGMOID_H_SIZE - 1] / (float)LUT_SIGMOID_H_SCALE;

    float  pos  = (x - LUT_SIGMOID_H_START) * LUT_SIGMOID_H_INV_STEP;
    int    idx  = (int)pos;
    float  frac = pos - (float)idx;
    float  y0   = (float)lut_sigmoid[idx];
    float  y1   = (float)lut_sigmoid[idx + 1];
    return (y0 + frac * (y1 - y0)) / (float)LUT_SIGMOID_H_SCALE;
}

#endif /* LUT_SIGMOID_H */
