#ifndef SMOKE_DETECTOR_MODEL_FLOAT_H
#define SMOKE_DETECTOR_MODEL_FLOAT_H

#include <stdint.h>

// Generated by hasaki dev
// Architecture: 12-8-4-1
// Quantization: float
// Activation sigmoid replaced by kigu-quant LUT — no expf(), no math.h

// ===== INPUT NORMALIZATION METADATA =====
// Normalize inputs BEFORE calling predict():
// for (int i = 0; i < 12; i++)
//     input[i] = (raw_input[i] - INPUT_MIN[i]) / (INPUT_MAX[i] - INPUT_MIN[i]);
// predict(input, output);

#include "lut_sigmoid.h"  // kigu-quant generated — replaces expf()-based sigmoid

static inline float relu(float x)        { return x > 0.0f ? x : 0.0f; }

const float w1[8][12] = {
    {-0.5729813f, 0.2282119f, 14.92596f, 4.168101f, 2.169844f, 1.22163f, -0.4932539f, 8.588444f, 4.318211f, 13.39233f, 4.56583f, -2.29332f},
    {1.880828f, -2.824744f, 0.5911402f, 0.8065286f, 1.089338f, 1.670717f, -8.246022f, 2.033785f, 0.3816322f, 1.93276f, -0.02795965f, -1.189951f},
    {0.7832904f, 0.155963f, -24.70054f, -27.85274f, -0.6741091f, -1.634858f, 2.33854f, -67.24309f, -65.38373f, -67.90533f, -65.37283f, -27.10268f},
    {-0.1781977f, -0.01096276f, -24.64672f, -10.7148f, -1.128538f, -0.4504873f, 0.4038083f, -66.93163f, -66.12043f, -68.07806f, -66.22495f, -24.19391f},
    {-0.3220179f, 0.4618585f, -0.0366981f, 0.248629f, -0.51257f, 0.07282485f, -0.2360086f, -0.1202992f, -0.1115888f, -0.5608204f, -0.5163983f, -0.08837665f},
    {-0.2646366f, -0.2573946f, 11.7185f, 0.1662807f, 1.092695f, 0.4289224f, -2.137797f, 1.652408f, 1.406105f, 1.777593f, 2.05156f, 1.945408f},
    {-0.1466378f, -0.3492215f, 0.2612868f, -0.8283263f, -0.2112056f, -0.1122352f, -0.5559504f, -0.3281446f, 0.4870939f, 0.3473815f, 0.06862034f, -0.5028023f},
    {-0.7544217f, -0.0727045f, -25.07951f, -10.02104f, -0.6311578f, -0.3971139f, 0.3979189f, -67.06928f, -65.98863f, -67.18644f, -66.27216f, -24.03821f}
};
const float b1[8] = {-1.218781f, 0.6257682f, 1.424613f, 1.128083f, -0.02679822f, 0.9555764f, 0.0f, 1.032905f};

const float w2[4][8] = {
    {-1.094007f, -0.1462528f, 0.9762284f, -5.671304f, -0.9844688f, 1.971484f, -0.6494373f, -3.84023f},
    {-0.5892589f, 4.536808f, -10.13947f, -0.1780799f, -0.01957734f, 1.198953f, 0.2346759f, 1.876099f},
    {-0.8199644f, -0.2543072f, -0.3794379f, 0.01421979f, 0.2024474f, 0.1293448f, 0.4813164f, 0.2680697f},
    {-4.098052f, -3.825213f, 2.134344f, 3.437542f, 0.4472728f, 10.23534f, 0.4361182f, 3.731725f}
};
const float b2[4] = {0.0619547f, -0.03446452f, -0.06491487f, -1.730009f};

const float w3[1][4] = {
    {10.69611f, 3.965784f, -0.6581394f, -36.027f}
};
const float b3[1] = {6.977754f};

static inline void predict(const float* input, float* output) {
    float a[8], b[8];
    const float* in = input;
    float* out = a;

    // layer 1 (relu)
    for (int i = 0; i < 8; i++) {
        float sum = b1[i];
        for (int j = 0; j < 12; j++)
            sum += w1[i][j] * in[j];
        out[i] = relu(sum);
    }
    in = out; out = (out == a) ? b : a;

    // layer 2 (relu)
    for (int i = 0; i < 4; i++) {
        float sum = b2[i];
        for (int j = 0; j < 8; j++)
            sum += w2[i][j] * in[j];
        out[i] = relu(sum);
    }
    in = out; out = (out == a) ? b : a;

    // layer 3 (sigmoid via kigu-quant LUT — no expf())
    for (int i = 0; i < 1; i++) {
        float sum = b3[i];
        for (int j = 0; j < 4; j++)
            sum += w3[i][j] * in[j];
        out[i] = lut_sigmoid_lookup(sum);
    }

    for (int i = 0; i < 1; i++)
        output[i] = out[i];
}

#endif // SMOKE_DETECTOR_MODEL_FLOAT_H
